// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsYbVUtyeJCPHwRdtXXzkYSf4DPx3l0hI',
    appId: '1:648110078757:web:b7dd46c12f799d9ec8f8cc',
    messagingSenderId: '648110078757',
    projectId: 'stamped-app-80cf8',
    authDomain: 'stamped-app-80cf8.firebaseapp.com',
    storageBucket: 'stamped-app-80cf8.firebasestorage.app',
    measurementId: 'G-FZEJKYH2H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0E0pfltuWe3QTUmsvLbCsS-44c1hID2w',
    appId: '1:648110078757:android:b7aac0b66dc9e8c1c8f8cc',
    messagingSenderId: '648110078757',
    projectId: 'stamped-app-80cf8',
    storageBucket: 'stamped-app-80cf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPdqE-kMAf4M71-2PoxhXS5LfFFbKaoiE',
    appId: '1:648110078757:ios:f56dec24c003383cc8f8cc',
    messagingSenderId: '648110078757',
    projectId: 'stamped-app-80cf8',
    storageBucket: 'stamped-app-80cf8.firebasestorage.app',
    iosClientId: '648110078757-h7j9rnrf7ng2cg050k3g0dec90d4tfof.apps.googleusercontent.com',
    iosBundleId: 'com.example.stamped',
  );
}
